# Generated by Django 5.0.4 on 2024-04-06 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nomComplet', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('M', 'M.'), ('MME', 'Mme.')], max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('HP', 'Hors Prêt'), ('DI', 'Disponible'), ('PE', 'Perdu'), ('RE', 'Retiré')], default='HP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour', models.DateTimeField()),
                ('rendu', models.BooleanField(default=False)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrages.exemplaire')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('recommended', models.BooleanField(blank=True, default=False)),
                ('exemplaires_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('auteurs', models.ManyToManyField(blank=True, to='ouvrages.auteur')),
                ('categories', models.ManyToManyField(blank=True, to='ouvrages.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='ouvrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrages.ouvrage'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reservation', models.DateTimeField()),
                ('acceptee', models.BooleanField(default=False)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrages.exemplaire')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrages.ouvrage')),
            ],
        ),
    ]
