# Generated by Django 5.0.4 on 2024-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
