# Generated by Django 5.0.3 on 2024-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0002_ouvrage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplaire',
            name='emprunté',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='réservé',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='acceptee',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
