# Generated by Django 5.0.3 on 2024-04-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0004_alter_emprunt_id_alter_exemplaire_id_alter_rayon_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exemplaire',
            old_name='emprunté',
            new_name='emprunte',
        ),
        migrations.RenameField(
            model_name='exemplaire',
            old_name='réservé',
            new_name='reserve',
        ),
    ]
