# Generated by Django 5.0.4 on 2024-05-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherants', '0001_initial'),
        ('ouvrages', '0005_rename_emprunté_exemplaire_emprunte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adherants.profile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adherants.profile'),
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adherants.profile'),
        ),
    ]
