# Generated by Django 5.0.4 on 2024-05-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0006_emprunt_emprunteur_reservation_owner_review_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='emprunte',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='acceptee',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='exemplaire',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_retour_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ouvrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ouvrages.ouvrage'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='etat',
            field=models.CharField(choices=[('HORS_PRET', 'Hors Prêt'), ('DISPONIBLE', 'Disponible'), ('PERDU', 'Perdu'), ('RETIRE', 'Retiré')], default='DISPONIBLE', max_length=20),
        ),
    ]
