# Generated by Django 5.0.4 on 2024-05-05 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0008_alter_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='selected_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ouvrages.exemplaire'),
        ),
    ]
