# Generated by Django 5.0.4 on 2024-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0009_reservation_selected_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplaire',
            name='etat',
            field=models.CharField(choices=[('HORS_PRET', 'Hors Prêt'), ('DISPONIBLE', 'Disponible'), ('PERDU', 'Perdu'), ('RETIRE', 'Retiré'), ('A_ENLEVER', 'À enlever')], default='DISPONIBLE', max_length=20),
        ),
    ]
