# Generated by Django 5.0.4 on 2024-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0010_alter_exemplaire_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='destroyed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(default=False),
        ),
    ]
