# Generated by Django 5.0.4 on 2024-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0011_emprunt_destroyed_alter_emprunt_date_retour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='destroyed',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='rendu',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
