# Generated by Django 5.0.4 on 2024-05-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0012_remove_emprunt_destroyed_alter_emprunt_rendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplaire',
            name='barcode',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
        ),
    ]
