# Generated by Django 5.0.4 on 2024-05-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0013_exemplaire_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
