# Generated by Django 5.0.3 on 2024-05-17 16:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherants', '0004_reclamation_useremail'),
        ('ouvrages', '0014_remove_exemplaire_barcode_alter_exemplaire_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_emprunt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='adherants.profile'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='exemplaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='ouvrages.exemplaire'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='adherants.profile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='selected_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='ouvrages.exemplaire'),
        ),
    ]
