# Generated by Django 5.0.4 on 2024-05-19 17:34

from django.db import migrations

def update_recommended_field(apps, schema_editor):
    Ouvrage = apps.get_model('ouvrages', 'Ouvrage')
    for ouvrage in Ouvrage.objects.all():
        if ouvrage.vote_ratio > 80:
            ouvrage.recommended = True
        else:
            ouvrage.recommended = False
        ouvrage.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0014_remove_exemplaire_barcode_alter_exemplaire_id'),
    ]

    operations = [
        migrations.RunPython(update_recommended_field),
    ]
