# Generated by Django 5.0.4 on 2024-05-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0015_auto_20240519_1834'),
    ]

    operations = [
    ]
