# Generated by Django 5.0.3 on 2024-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0015_alter_emprunt_date_emprunt_alter_emprunt_emprunteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='automatique',
            field=models.BooleanField(default=False),
        ),
    ]
