# Generated by Django 5.0.4 on 2024-05-19 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0016_auto_20240519_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exemplaire',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='ouvrage',
            options={'ordering': ['-vote_ratio', '-vote_total', 'titre']},
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]


