# Generated by Django 5.0.4 on 2024-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0017_alter_exemplaire_options_alter_ouvrage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplaire',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
