# Generated by Django 5.0.3 on 2024-05-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0017_alter_reservation_date_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='confirmer',
            field=models.BooleanField(default=False),
        ),
    ]
