# Generated by Django 5.0.3 on 2024-05-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0018_emprunt_confirmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='confirmer',
            new_name='confirme',
        ),
    ]
