# Generated by Django 5.0.3 on 2024-05-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0019_rename_confirmer_emprunt_confirme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='confirme',
            new_name='confirmer',
        ),
    ]
