# Generated by Django 5.0.3 on 2024-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0020_rename_confirme_emprunt_confirmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='automatique',
            field=models.BooleanField(default=True),
        ),
    ]
