# Generated by Django 5.0.4 on 2024-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherants', '0002_remove_profile_name_profile_nom_profile_prenom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
