# Generated by Django 5.0.4 on 2024-05-03 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherants', '0003_alter_profile_options_profile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(blank=True, default=False, max_length=200)),
                ('email', models.EmailField(blank=True, default=False, max_length=254)),
                ('message', models.TextField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
