# Generated by Django 5.0.3 on 2024-05-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherants', '0004_reclamation_useremail'),
        ('ouvrages', '0022_merge_20240520_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='ouvrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ouvrages.ouvrage'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='sujet',
            field=models.TextField(blank=True, default=False),
        ),
    ]
